delimiter $$

CREATE TABLE `alumnos` (
  `ALM_DNI` int(11) NOT NULL,
  `ALM_PASSWORD` varchar(255) NOT NULL,
  `ALM_NOMBRE` varchar(255) NOT NULL,
  `ALM_TELEFONO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ALM_DNI`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

delimiter $$

CREATE TABLE `asignaturas` (
  `ASIGN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ASIGN_CODIGO` int(11) NOT NULL,
  `ASIGN_NOMBRE` varchar(255) NOT NULL,
  `ASIGN_CREDITOS` float DEFAULT NULL,
  `PROF_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ASIGN_ID`),
  UNIQUE KEY `ASIGN_CODIGO` (`ASIGN_CODIGO`),
  KEY `FKAAB0CD40F489D67A` (`PROF_ID`),
  CONSTRAINT `FKAAB0CD40F489D67A` FOREIGN KEY (`PROF_ID`) REFERENCES `profesores` (`PROF_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1$$

delimiter $$

CREATE TABLE `evaluaciones` (
  `EVAL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EVAL_CONCEPTO` varchar(255) NOT NULL,
  `EVAL_NOTA` float NOT NULL,
  `ASIGN_ID` int(11) NOT NULL,
  `ALM_DNI` int(11) NOT NULL,
  PRIMARY KEY (`EVAL_ID`),
  KEY `FK8563BA5B12E4C695` (`ALM_DNI`),
  KEY `FK8563BA5B26AA59DE` (`ASIGN_ID`),
  CONSTRAINT `FK8563BA5B12E4C695` FOREIGN KEY (`ALM_DNI`) REFERENCES `alumnos` (`ALM_DNI`),
  CONSTRAINT `FK8563BA5B26AA59DE` FOREIGN KEY (`ASIGN_ID`) REFERENCES `asignaturas` (`ASIGN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1$$

delimiter $$

CREATE TABLE `matriculado` (
  `ALM_DNI` int(11) NOT NULL,
  `ASIGN_ID` int(11) NOT NULL,
  PRIMARY KEY (`ALM_DNI`,`ASIGN_ID`),
  KEY `FK48D1366912E4C695` (`ALM_DNI`),
  KEY `FK48D1366926AA59DE` (`ASIGN_ID`),
  CONSTRAINT `FK48D1366912E4C695` FOREIGN KEY (`ALM_DNI`) REFERENCES `alumnos` (`ALM_DNI`),
  CONSTRAINT `FK48D1366926AA59DE` FOREIGN KEY (`ASIGN_ID`) REFERENCES `asignaturas` (`ASIGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

delimiter $$

CREATE TABLE `profesores` (
  `PROF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROF_DNI` int(11) DEFAULT NULL,
  `PROF_PASSWORD` varchar(255) DEFAULT NULL,
  `PROF_NOMBRE` varchar(255) NOT NULL,
  `PROF_TFNO` varchar(255) DEFAULT NULL,
  `PROF_EMAIL` varchar(255) DEFAULT NULL,
  `PROF_DESPACHO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PROF_ID`),
  UNIQUE KEY `PROF_NOMBRE` (`PROF_NOMBRE`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1$$

delimiter $$

CREATE TABLE `unidades` (
  `UD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `UD_ACRONIMO` varchar(255) NOT NULL,
  `UD_TITULO` varchar(255) NOT NULL,
  `UD_CONTENIDO` longtext,
  `ASIGN_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`UD_ID`),
  UNIQUE KEY `UD_ACRONIMO` (`UD_ACRONIMO`),
  KEY `FK1C588B8526AA59DE` (`ASIGN_ID`),
  CONSTRAINT `FK1C588B8526AA59DE` FOREIGN KEY (`ASIGN_ID`) REFERENCES `asignaturas` (`ASIGN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1$$